apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpcalc-register-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpcalc-register-producer
  template:
    metadata:
      labels:
        app: mpcalc-register-producer
    spec:
      containers:
      - name: mpcalc-register-producer
        image: gabrielloureirog/mpcalchub-personal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mpcalc-config
