apiVersion: v1
kind: Service
metadata:
  name: mpcalc-register-producer-service
spec:
  type: NodePort
  selector:
    app: mpcalc-register-producer
  ports:
    - port: 80
      targetPort: 5022
      nodePort: 32001 